name: cfst
services:
  cfst:
    image: cfst:latest
    container_name: cfst
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
    volumes:
      - cfst:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - custom-network

volumes:
  cfst:
networks:
  custom-network:
    driver: bridge